# Generated by Django 6.0.2 on 2026-02-22 09:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLocationInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=210, null=True)),
                ('custom_field', models.JSONField(blank=True, default=dict, null=True)),
                ('is_default', models.BooleanField(default=True)),
                ('address_id', models.CharField(blank=True, max_length=30, null=True)),
                ('address_line_01', models.CharField(blank=True, max_length=70, null=True)),
                ('mobile_number_01', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_number_02', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=70, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('google_place_link', models.CharField(blank=True, max_length=220, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=210, null=True)),
                ('custom_field', models.JSONField(blank=True, default=dict, null=True)),
                ('expection_rate', models.CharField(blank=True, max_length=21, null=True)),
                ('applicant_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.employeecompanyinfo')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobApplicationStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=210, null=True)),
                ('custom_field', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=200, null=True)),
                ('job_applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplication')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=210, null=True)),
                ('custom_field', models.JSONField(blank=True, default=dict, null=True)),
                ('title', models.CharField(blank=True, max_length=220, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='job_document')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='job_document')),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Joblist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=210, null=True)),
                ('custom_field', models.JSONField(blank=True, default=dict, null=True)),
                ('position', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('experience', models.IntegerField(default=0)),
                ('reference_name', models.CharField(blank=True, max_length=210, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=8, null=True)),
                ('vacancies', models.CharField(blank=True, max_length=8, null=True)),
                ('budget', models.CharField(blank=True, max_length=15, null=True)),
                ('payment_type', models.JSONField(blank=True, default=list)),
                ('expried_date', models.DateTimeField(null=True)),
                ('attachment_ids', models.JSONField(blank=True, default=list)),
                ('provider_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.employeecompanyinfo')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.joblocationinfo')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=210, null=True)),
                ('custom_field', models.JSONField(blank=True, default=dict, null=True)),
                ('work_start_date', models.DateTimeField(blank=True, null=True)),
                ('work_end_date', models.DateTimeField(blank=True, null=True)),
                ('payment_details', models.CharField(blank=True, max_length=220, null=True)),
                ('jobApplicationStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplicationstatus')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.joblist')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='jobapplicationstatus',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.joblist'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.joblist'),
        ),
    ]
