# Generated by Django 6.0.2 on 2026-02-22 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDesignation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=210, null=True)),
                ('custom_field', models.JSONField(blank=True, default=dict, null=True)),
                ('name', models.CharField(blank=True, max_length=220, null=True)),
                ('tag', models.CharField(blank=True, max_length=220, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_job_seeker', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companymeta')),
                ('company_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companybranchinfo')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompanyInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=210, null=True)),
                ('custom_field', models.JSONField(blank=True, default=dict, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=40, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_document')),
                ('token', models.TextField(blank=True, null=True)),
                ('is_token_valid', models.BooleanField(default=False)),
                ('authentication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.userauthentication')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companymeta')),
                ('company_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companybranchinfo')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companydepartment')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_referrer', to='users.employeecompanyinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userdesignation')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPersonalInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=210, null=True)),
                ('custom_field', models.JSONField(blank=True, default=dict, null=True)),
                ('gender', models.CharField(max_length=5)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('aadhar', models.CharField(blank=True, max_length=130, null=True)),
                ('address', models.CharField(blank=True, max_length=130, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=70, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('authentication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.userauthentication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfessionalInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=210, null=True)),
                ('custom_field', models.JSONField(blank=True, default=dict, null=True)),
                ('skills', models.CharField(blank=True, max_length=220, null=True)),
                ('position', models.CharField(blank=True, max_length=220, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Experience', models.IntegerField(default=0)),
                ('available_days_category', models.CharField(blank=True, choices=[('weekday', 'Weekdays (Mon–Fri)'), ('weekend', 'Weekend (Sat–Sun)'), ('custom', 'Custom Days')], max_length=20, null=True)),
                ('custom_days', models.JSONField(blank=True, default=list)),
                ('rating', models.CharField(blank=True, max_length=5, null=True)),
                ('portfolio_photo', models.ImageField(blank=True, null=True, upload_to='portfolio_photos/')),
                ('user_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.employeecompanyinfo')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
